name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: PruebaActions

    steps:
      - name: Working dir
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"
    