name: Deploy to server

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: PruebaActions

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: actions/checkout@v4

  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"
    